apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypal-service
  labels:
spec:
  app: paypal-service
  replicas: 1
  template:
    metadata:
      labels:
        app: paypal-service
    spec:
      containers:
        - name: paypal-service
          image: puje2docker/paypal-service:latest
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: paypal-service
