apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: puje2docker/payment-service:latest
          ports:
            - containerPort: 8080
              env:                  # Environment variables supplied to the Pod
                - name: SPRING_DATASOURCE_USERNAME # Name of the environment variable
                  valueFrom:          # Get the value of environment variable from kubernetes secrets
                    secretKeyRef:
                      name: mysql-payment-service-secrets
                      key: MYSQL_USER
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-payment-service-secrets
                      key: MYSQL_PASSWORD
                - name: SPRING_DATASOURCE_URL
                  valueFrom:
                    secretKeyRef:
                      name: mysql-payment-service-secrets
                      key: MYSQL_URL
                - name: SERVER_PORT
                  valueFrom:
                    secretKeyRef:
                      name: mysql-payment-service-secrets
                      key: SERVER_PORT
  selector:
    matchLabels:
      app: payment-service
