apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  labels:
spec:
  app: orders-service
  replicas: 1
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: puje2docker/orders-service:latest
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: orders-service
