apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  labels:
    app: deployment-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-service
    spec:
      containers:
        - name: deployment-service
          image: puje2docker/deployment-service:latest
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: deployment-service
