apiVersion: apps/v1
kind: Service
metadata:
  name: credit-service
  labels:
    app: credit-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: credit-service
