apiVersion: apps/v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-service
spec:
  type: ClusterIP
  ports
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: db-service
